@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 25 14:11:57 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim stop_watch_tb_behav -key {Behavioral:sim_1:Functional:stop_watch_tb} -tclbatch stop_watch_tb.tcl -view C:/Users/xy424/Documents/VivadoRepository/lab9_3_1/stop_watch_tb_behav.wcfg -log simulate.log"
call xsim  stop_watch_tb_behav -key {Behavioral:sim_1:Functional:stop_watch_tb} -tclbatch stop_watch_tb.tcl -view C:/Users/xy424/Documents/VivadoRepository/lab9_3_1/stop_watch_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
