@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jul 05 09:19:02 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Parallel_in_serial_out_load_enable_behavior_tb_behav -key {Behavioral:sim_1:Functional:Parallel_in_serial_out_load_enable_behavior_tb} -tclbatch Parallel_in_serial_out_load_enable_behavior_tb.tcl -view C:/Users/xy424/Documents/VivadoRepository/lab6_1_4/Parallel_in_serial_out_load_enable_behavior_tb_behav.wcfg -log simulate.log"
call xsim  Parallel_in_serial_out_load_enable_behavior_tb_behav -key {Behavioral:sim_1:Functional:Parallel_in_serial_out_load_enable_behavior_tb} -tclbatch Parallel_in_serial_out_load_enable_behavior_tb.tcl -view C:/Users/xy424/Documents/VivadoRepository/lab6_1_4/Parallel_in_serial_out_load_enable_behavior_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
